### ISSUE TITLE
lost intrins in IPM transformation

### ISSUE THREAD

**Issue by JadoTu** [Tsinghua-MARS-Lab/HDMapNet#31]
Hello,

I have some questions when reviewing the code base. I know the function of IPM Net in the model. I think the grid plane (BEV map) should transfer to the pixel level coordinate system based on the code logics. That's to say, the Ln 192 and 193 of homography.py is to multiply the external trins, intrins, and post_RTs to transform the grid plane.
However, the Ks (intrins) seems to be an identity matrix because the Ln 71 of the hdmapnet.py is empty. The Ks is not initialized by the intrins of the camera. It seems a strange error here.
By the way, why the post_RTs is None at the Ln 78 of the hdmapnet.py? It should be none or it is an error?

**Comment by liqi0126** [comment]
Hi, the behaviors you are expecting are modeled at imp_net.py, where Ks and post_RTs are intrinsics and post extrinsics (and they are not empty for sure). But for HDMapNet, since we use fully-connected layers to learn the transformation implicitly, we only need to project the learned features into a common plane with the extrinsics.

**Comment by JadoTu** [comment]
I got it. Thanks!
